name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Push Docker images 
      run: mvn package --file pom.xml -Pdocker -DskipTests -Ddocker.repo=helidonsockshop -Djib.goal=build
